version: '3.8'

services:
  api-service:
      image: luongquoctay87/sample-java-app:v1.0.0
      container_name: api-service
      environment:
        - DB_URL=database-1.ctixzu74yr0p.ap-southeast-1.rds.amazonaws.com
        - DB_NAME=db_test
        - DB_USER=admin
        - DB_PASSWORD=12345678
      ports:
        - "8080:8080"
      volumes:
        - ./:/app
      networks:
        - backend

  prometheus:
    image: "prom/prometheus"
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: "grafana/grafana"
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    name: api-network
